in_channels: 128
resblock_dilation_sizes:
  - [1, 3, 5]
  - [1, 3, 5]
  - [1, 3, 5]
resblock_kernel_sizes: [3, 7, 11]
upsample_kernel_sizes: [20, 8, 4, 4]
upsample_initial_channel: 128
upsample_factors: [10, 4, 2, 2]
inference_padding: 5
sample_rate: 16000